### ISSUE TITLE
Issue when multiply and divide

### ISSUE THREAD

**Issue by TharHtwe** [scegg/Fraction#1]
Incorrect result when multiply and divide
new Fraction("2") * new Fraction("1/2") result 3
new Fraction("2") / new Fraction("1/2") result 6

**Comment by scegg** [comment]
Thanks for your report.
Checking on the way.

**Comment by scegg** [comment]
Bug located. Source is updated. Please allow 1-2 hrs for nuget refreshing.

**Comment by scegg** [comment]
I close this issue for now. If there is still any problem related, please re-open it. Thanks.

**Comment by scegg** [comment]
I close this issue for now. If there is still any problem related, please re-open it. Thanks.
